### ISSUE TITLE
Deprecation warning for formatargspec in Python3.7

### ISSUE THREAD

**Issue by clippered** [jonathanslenders/asyncio-redis#127]
Minor issue:
`
python3.7/site-packages/asyncio_redis/protocol.py:549: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
`

**Comment by ntoll** [comment]
Ditto... I see this when using PyTest:

```
<snip/>/python3.7/site-packages/asyncio_redis/protocol.py:549: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
    signature = formatargspec(* self.specs[:6])
```
