### ISSUE TITLE
Python 3.8 DeprecationWarnings; drop support for legacy Python

### ISSUE THREAD

**Issue by crusaderky** [jonathanslenders/asyncio-redis#133]
On Python 3.8, any application using asyncio_redis inundates the log with:

> lib/python3.8/site-packages/asyncio_redis/protocol.py:805: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
    self._transaction_lock = asyncio.Lock(loop=loop)

> lib/python3.8/site-packages/asyncio_redis/protocol.py:831: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
    def initialize():

I don't think the problem is solvable without dropping support for Python < 3.5.
I would love to see asyncio-redis adopt NEP-29 <https://numpy.org/neps/nep-0029-deprecation_policy.html>, which would mean dropping support for Python < 3.6.

We've already pushed NEP-29 to the xarray and pint projects, with great satisfaction of all developers and zero complaints from the users.

**Comment by jonathanslenders** [comment]
@crusaderky : I don't mind dropping Python 3.5. Are you willing to work on this change?

**Comment by jonathanslenders** [comment]
See also: https://github.com/jonathanslenders/asyncio-redis/issues/134

**Comment by crusaderky** [comment]
Yes I'm happy to work on it
