### ISSUE TITLE
Retrieve a value between WATCH and MULTI

### ISSUE THREAD

**Issue by Martiusweb** [jonathanslenders/asyncio-redis#62]
Hi,

As far as I understand, `WATCH` allows to monitor keys for concurrent update so a future transaction (started by `MULTI`) will fail if the watched keys have been modified by a concurrent connection since watched.

A common use case would then be:

    WATCH key
    value = GET key
    # update value
    MULTI
    SET key value
    EXEC

However, since the only way to execute the `WATCH` command is via `multi(watch=[key])`, it's not possible to retrieve a value between the call to `WATCH` and the call to `MULTI`.

Did I miss something or would it make sense to add a `RedisProtocol.watch()` method for this case?
I'd gladly work on the issue and submit a pull request if you think it makes sense.

Cheers

**Comment by jonathanslenders** [comment]
Hi @Martiusweb,

I'm closing this one. I think everything was done when we merged the pull request.
If not, feel free to reopen.

Jonathan
