### ISSUE TITLE
Default arguments are not encoded correctly.

### ISSUE THREAD

**Issue by brunsgaard** [jonathanslenders/asyncio-redis#67]
We store serialized protocol buffers in Redis, thus we need to use the `asyncio_redis.encoders.BytesEncoder`. I have been using the last hour goung through the `asyncio-redis` code to understand why my `sscan` failed. I found out that scan with type annotations was defined as shown below and `match` has a default argument with the value `'*'`,

    def sscan(self, key:NativeType, match:NativeType='*') -> SetCursor:

This will result in the `input_typecheck` function throwing a `TypeError`. A quick fix is of cause just to overwrite the default argument match with `b'*'`, but this should be done somewhere in the type checking system instead.

**Comment by jonathanslenders** [comment]
Very good catch! I see what is happening. I'll try to figure out how to solve this.

**Comment by brunsgaard** [comment]
@jonathanslenders, thank you ;) appreciated <3

**Comment by jonathanslenders** [comment]
Hi @brunsgaard,

Excuse me for the delay! I hope this didn't cause to many issues for you.
It has been fixed now: https://github.com/jonathanslenders/asyncio-redis/commit/c4dbb5bfb6a1f7210e8913bc52acf031434a9dd7

I'm going to do a new resease with a few more fixes soon.
Jonathan
