### ISSUE TITLE
RedisProtocol.rpush received 'str', expected (<class 'list'>, <class 'generator'>)

### ISSUE THREAD

**Issue by KKfo** [jonathanslenders/asyncio-redis#89]
I get this when trying to push a python string to a list:
 ```exception=TypeError("RedisProtocol.rpush received 'str', expected (<class 'list'>, <class 'generator'>)",)>```

Am i missing something here.

Thanks.

**Comment by jonathanslenders** [comment]
Hi @KKfo,
Try this:
```python
connection.rpush(key, ['value'])
```
rpush expects values to be a list, because many values can be pushed in one call. (http://asyncio-redis.readthedocs.org/en/latest/pages/reference.html#asyncio_redis.RedisProtocol.rpush)

Does that work?
Jonathan

**Comment by KKfo** [comment]
Thanks for the help @jonathanslenders thats what i did after i got the error and i was wandering why the function takes a list.  And yes that works.

**Comment by jonathanslenders** [comment]
You're welcome!
